workflows:
  version: 2
  triggers:
    branches:
      only:
        -master
  jobs:
    build:
      docker:
        - image: circleci/node:10
      working_directory: ~/tmp
      steps:
        - checkout
        - run: npm install
        - run: npm run test