---
  version: 2.0
  jobs: 
    build: 
      machine: true
      steps: 
        - run: ls -la
        - run: pwd
    
    deploy: 
      docker:
        - image: circleci/node:8
      steps: 
        - run: ls -la 
        - run: cd /etc
        - run: ls -la

  workflows:
    version: 2
    # filters:
    #   branches:
    #     only:
    #       - master
    build_and_test:
      jobs:
        - build
        - deploy
        