version: 2
jobs:
  build:
    machine: true
    steps:
        - run: ls
# job2:
#   build:
#     docker:
#       -image:  circleci/node:10  
#     steps:
#       -run: pwd

# workflows:
#   job1
#   job2