version: 2
jobs:
  build:
    working_directory: ~/tmp
    branches:
      only:
        -master
    docker:
      - image: circleci/node:10
    steps:
      - checkout
        - run: npm install
        - run: npm run test