version: 2
jobs:
  build:
    machine: true
    steps:
      - run: ls
  job2:    
    docker:
      -image:  circleci/node:10  
    steps:
      - run: pwd

workflows:
  version: 2
  build_and_job2:
    jobs:
      - build
      - job2